# Generated by Django 5.0 on 2024-01-03 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_post_current_amount_remove_post_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='post',
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Donate', 'Donate'), ('Get', 'Get')], default=None, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='userchoice',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='app.userchoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='userchoice',
            field=models.ForeignKey(default=213, on_delete=django.db.models.deletion.CASCADE, to='app.userchoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='get',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userchoice'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
