# Generated by Django 5.0 on 2024-01-03 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_comment_post_remove_donation_post_userchoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Get',
            new_name='GetDonation',
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='category',
            field=models.CharField(choices=[('Donate', 'Donate'), ('Get Donation', 'Get Donation')], default=None, max_length=20),
        ),
    ]
