# Generated by Django 4.1 on 2024-01-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_get_getdonation_alter_userchoice_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getdonation',
            old_name='post',
            new_name='userchoice',
        ),
    ]
