# Generated by Django 5.0 on 2024-01-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_img_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='getdonation',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='app.getdonation'),
            preserve_default=False,
        ),
    ]
