# Generated by Django 4.1 on 2024-01-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=21, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
